### ISSUE TITLE
Fontsize of labels changes to 0

### ISSUE THREAD

**Issue by T4rikA** [hpi-swa-lab/qinoq#1019]
**Describe the bug**
The size of labels became 0 in the user test

**To Reproduce**
not clear, try zooming the interactive and loading/ unloading it

**Comment by linusha** [comment]
The current implementation allows for the fontSize to become 0 when making the interactive smaller. Once it is 0, it will never become larger again, because the current fontSize is  factor in the calculation of the new fontSize. Fixing this is easy, as one does only need to exchange the call to `Math.round()` with `Math.ceil()`.

However, the scaling is also non-revertible at the moment. E.g. once one reaches a fontSize of 1, reverting the extent will lead to e..g, much larger text.

**Comment by linusha** [comment]
Fixed with 2f2c6bcc8c4d239a581d2bd561dc30fc67cb155b.
